export type SkillLevel = 'beginner' | 'intermediate' | 'advanced';
export type TechniqueStatus = 'not-started' | 'learning' | 'mastered' | 'skipped';

/**
 * A single step within a lesson. The AI generates these as
 * self-contained instructional blocks so the user never needs
 * to leave the app to learn.
 */
export interface LessonStep {
  order: number;
  title: string;
  body: string;
}

/**
 * A focused practice drill the user can follow after reading
 * through the lesson steps. Includes a clear goal and duration.
 */
export interface PracticeExercise {
  title: string;
  instruction: string;
  durationMinutes: number;
  goal: string;
}

/**
 * Compact expert advice surfaced at the end of each lesson
 * to reinforce the most critical points.
 */
export interface KeyTakeaway {
  title: string;
  detail: string;
}

/**
 * Complete lesson content generated by the AI for a single technique.
 * This replaces the old `Resource[]` model that linked out to
 * YouTube/Google. All content is rendered natively in the app.
 */
export interface LessonContent {
  overview: string;
  steps: LessonStep[];
  exercise: PracticeExercise;
  proTips: string[];
}

/**
 * A single technique within a learning plan. Each technique contains
 * its own self-contained lesson, generated entirely by the AI.
 */
export interface Technique {
  id: string;
  name: string;
  description: string;
  category: string;
  estimatedMinutes: number;
  level: SkillLevel;
  status: TechniqueStatus;
  masteredAt?: number;
  reviewDueAt?: number;
  lesson: LessonContent;
  keyTakeaways: KeyTakeaway[];
}

export interface LearningPlan {
  hobby: string;
  targetLevel: SkillLevel;
  techniques: Technique[];
  createdAt: number;
  streakCount: number;
  lastPracticeDate?: string;
}
